### ISSUE TITLE
After building in production mode, original (un-revisioned) files should be removed

### ISSUE THREAD

**Issue by cheapsteak** [leonidas/gulp-project-template#28]
I wonder if you've already looked into how hard it'll be to directly build the revisioned files?   
The template task would have to wait for the script and css tasks to finish, then could maybe use [gulp-inject](https://www.npmjs.com/package/gulp-inject) to add the tags?

**Comment by rikukissa** [comment]
I guess it wouldn't be that hard to do and it might just make the whole revisioning flow a little cleaner. Wanna try and send a pull request?

**Comment by rikukissa** [comment]
Also, it would be awesome if we could get rid of the rev-manifest.json file which is currently there just to pass the revision filenames from "revision" task to "replace-revision-references" task. Ugly.

**Comment by cheapsteak** [comment]
yup, wanna try :D
