### ISSUE TITLE
Converting gulpfile to ES6+ syntax

### ISSUE THREAD

**Issue by rikukissa** [leonidas/gulp-project-template#29]
Would this make any sense? It seems that gulp 3.9 uses babel-core to load the gulpfile if the file is named `gulpfile.babel.js` [(source)](https://markgoodyear.com/2015/06/using-es6-with-gulp/). To me, that feels a little nasty, but it would make sense to have the gulpfile in ES6+ if other parts of your application is written in it.

**Comment by cheapsteak** [comment]
Definitely jarring to have the gulpfile be written in a different syntax than the rest of the project  
Don't think the name is that bad. 

The only alternative I can see without doing that is  
```
"scripts": {
  "gulpfile": "babel gulpfile.js -o .gulpfile.js",
  "gulp": "npm run gulpfile && gulp --gulpfile .gulpfile.js",
  "start": "npm run gulp",
  "build": "npm run gulp build",
},
```
And use `npm run start` and `npm run build`  

You can still run individual gulp tasks via `npm run gulp templates`, `npm run gulp styles` etc

can try it out here: https://github.com/leonidas/gulp-project-template/compare/master...cheapsteak:gulp-es6?expand=1

`gulpfile.babel.js` definitely seems like the simplest solution though

**Comment by rikukissa** [comment]
Well maybe `gulpfile.babel.js` isn't that bad after all... I'd prefer it was just gulpfile.js that's automatically run through babel, but maybe that would be too implicit and cause problems. Using a script named gulpfile seems a bit awkward :smile: 
`gulpfile.babel.js` it is IMO. 

I don't know if we achieve any major benefits by converting the buildfile to ES6. One thing I've been struggling though, is eslint rules like `no-var` that cannot be fulfilled when the config is written in ES5.

**Comment by cheapsteak** [comment]
Yup, consistency :)

**Comment by cheapsteak** [comment]
looks good! :+1:
