### ISSUE TITLE
Babel 6?

### ISSUE THREAD

**Issue by cheapsteak** [leonidas/gulp-project-template#36]
Is there any point in upgrading to babel 6?

**Comment by rikukissa** [comment]
IMO it's always good idea to keep our dependencies up-to-date :)

**Comment by cheapsteak** [comment]
Status update:

Babel 6 seems to have changed `inline-environment-variables` to `transform-inline-environment-variables`, but this seems to currently be broken :(

Here's the branch I have with babel 6 working _without_ the environment variable inliner
https://github.com/cheapsteak/gulp-project-template/tree/upgrade-babel

Here's a branch with the the inliner transform, but it's broken  
https://github.com/cheapsteak/gulp-project-template/tree/babel-env-inline

What are your thoughts on using [envify](https://www.npmjs.com/package/envify) or [loose-envify](https://www.npmjs.com/package/loose-envify) instead? They do the same thing but seem to have more community support

**Comment by rikukissa** [comment]
We actually had envify included earlier, but I replaced it with Babel's own environment inliner when it suddenly stopped working. If you manage to get it working Ill happily merge the pull requests :)
